package main

import (
	"context"
	"log"
	"net"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/reflection"
	"google.golang.org/grpc/status"
)

// ============================================================================
// 1. PROTOBUF MOCKS (Normally generated by protoc-gen-go & protoc-gen-go-grpc)
//
// syntax = "proto3";
// message Point { double lat = 1; double lon = 2; }
// message GetLocationRequest { string id = 1; }
// message GetLocationResponse { Point location = 1; }
// service SpatialService { rpc GetLocation(GetLocationRequest) returns (GetLocationResponse); }
// ============================================================================

type Point struct {
	Lat float64
	Lon float64
}

type GetLocationRequest struct {
	Id string
}

type GetLocationResponse struct {
	Location *Point
}

// SpatialServiceServer is the server API for SpatialService service.
type SpatialServiceServer interface {
	GetLocation(context.Context, *GetLocationRequest) (*GetLocationResponse, error)
}

// RegisterSpatialServiceServer registers the handler with the gRPC server.
// (Mocked simplified version of what grpc-go generates)
func RegisterSpatialServiceServer(s grpc.ServiceRegistrar, srv SpatialServiceServer) {
	// In reality, this binds the service description to the server instance.
	// We are mocking this for the single-file example.
}

// ============================================================================
// 2. REPOSITORY & BUSINESS LOGIC (Merged for simplicity)
// ============================================================================

// server implements the SpatialServiceServer interface.
type server struct {
	db *pgxpool.Pool
}

// GetLocation handles the incoming gRPC request, queries PostGIS, and formats the response.
func (s *server) GetLocation(ctx context.Context, req *GetLocationRequest) (*GetLocationResponse, error) {
	if req.Id == "" {
		return nil, status.Error(codes.InvalidArgument, "id is required")
	}

	// PostGIS Query: We use ST_Y (Lat) and ST_X (Lon) to extract floats from the geometry.
	// This avoids needing complex geometry parsing libraries for simple point extraction.
	query := `
		SELECT ST_Y(geom), ST_X(geom) 
		FROM spatial_locations 
		WHERE id = $1
	`

	var lat, lon float64
	err := s.db.QueryRow(ctx, query, req.Id).Scan(&lat, &lon)
	if err != nil {
		// Differentiate between "Not Found" and actual internal errors
		if err.Error() == "no rows in result set" {
			return nil, status.Errorf(codes.NotFound, "location with id %s not found", req.Id)
		}
		log.Printf("DB error querying location %s: %v", req.Id, err)
		return nil, status.Error(codes.Internal, "failed to retrieve location")
	}

	// Format and return the Protobuf response
	return &GetLocationResponse{
		Location: &Point{
			Lat: lat,
			Lon: lon,
		},
	}, nil
}

// ============================================================================
// 3. SERVER BOOTSTRAP (Main)
// ============================================================================

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	config, err = LoadConfig(logger)

	if err != nil {
		logger.Error("Failed to load config", slog.Any("error", err))
		os.Exit(1)
	}
	
	dbPoolConfig = BuildPoolConfig(config)

	dbPool, err := pgxpool.NewWithConfig(ctx, dbPoolConfig)
	if err != nil {
		slog.Error("Failed to initialize database pool: %v", err)
		os.Exit(1)
	}
	defer dbPool.Close()

	// Quick connection test
	ctxTimeout, cancelTimeout := context.WithTimeout(ctx, 2*time.Second)
	defer cancelTimeout()
	if err := dbPool.Ping(ctxTimeout); err != nil {
		slog.Warning("Could not ping database: %v", err)
	} else {
		log.Println("Connected to PostgreSQL/PostGIS.")
	}

	// 2. Initialize the gRPC Server and Handler
	grpcServer := grpc.NewServer()
	srv := &server{db: dbPool}

	// Normally you call the generated protobuf registration function here
	RegisterSpatialServiceServer(grpcServer, srv)

	// Enable reflection so tools like grpcurl or Postman can interact with it easily
	// reflection.Register(grpcServer)

	// 3. Setup Networking
	listener, err := net.Listen("tcp", ":8080")
	if err != nil {
		slog.Error("Failed to listen on port database pool: %v", err)
		os.Exit(1)
	}

	// 4. Graceful Shutdown
	go func() {
		quit := make(chan os.Signal, 1)
		signal.Notify(quit, os.Interrupt, syscall.SIGTERM)
		<-quit
		log.Println("Received shutdown signal. Stopping gRPC server gracefully...")
		grpcServer.GracefulStop()
		cancel()
	}()

	// 5. Start Serving
	log.Println("Starting spatial microservice on :8080")
	if err := grpcServer.Serve(listener); err != nil {
		log.Fatalf("gRPC server terminated with error: %v", err)
	}
}

func BuildPoolConfig(env Config) (*pgxpool.Config, error) {	
	// Start with an empty/default config
	config, err := pgxpool.ParseConfig("")
	if err != nil {
		return nil, err
	}

	// Mutate the connection config safely
	config.ConnConfig.Host = env.DatabaseHost
	config.ConnConfig.Port = env.DatabasePort
	config.ConnConfig.User = env.DatabaseUsername
	config.ConnConfig.Password = env.DatabasePassword
	config.ConnConfig.Database = env.DatabaseName

	// Hardcode the constraints required by your architecture
	// This prevents misconfiguration via environment variables
	config.ConnConfig.RuntimeParams = map[string]string{
		"default_query_exec_mode": "exec", // Mandatory for pgBouncer
		"sslmode":                 "disable", // Proxy handles TLS
	}

	return config, nil
}